fix: try to prevent go gc from cleaning up tokenIds slice (#48)
Try to fix a rare issue in the go bindings that manifests as this panic

```
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)"
```

I think this is because `tokenIds` was being incorrectly cleaned up by
the Go GC before the call to `C.melody_filter_write_decoded` completes.
Unfortunately I wasn't able to replicate the crash so this is a bit of a
speculative fix.